inertial_frame_id: world
waypoints:
  -
    point: [1105, 152, -5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [1096, 154, -14]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [1088, 160, -22]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [1081, 162, -25]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [1074, 166, -32]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [1069, 161, -39]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [1065, 158, -42]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [1060, 156, -47]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [1057, 154, -50]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
