inertial_frame_id: world
waypoints:
  -
    point: [60, -5, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [65, -8, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [72, -12, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [80, -15, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [85, -19, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [90, -22, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [95, -25, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [100, -28, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [105, -30, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
