inertial_frame_id: world
waypoints:
  -
    point: [50, 5, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [55, 8, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [62, 12, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [70, 15, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [79, 19, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [88, 22, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [95, 25, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 28, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [105, 30, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
