inertial_frame_id: world
waypoints:
  -
    point: [177, 2, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [182, 6, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [188, 9, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [193, 13, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [200, 17, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [205, 20, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [211, 26, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [216, 30, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [220, 32, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
