inertial_frame_id: world
waypoints:
  -
    point: [105, -32, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [110, -22, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [112, -19, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [121, -15, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [128, -11, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [133, -8, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [139, -2, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [144, 2, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [148, 4, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
