inertial_frame_id: world
waypoints:
  -
    point: [5, 0, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [10, 0, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [15, 0, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [20, 0, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 0, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [30, 0, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [35, 0, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [40, 0, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
  -
    point: [45, 0, 0]
    max_forward_speed: 0.8
    heading: 0
    use_fixed_heading: False
